1-5 パスワードの
takattty/ex-emp-management-bugfix pull request #10
Opened 2022-06-09 07:23 UTC by takattty

2022-06-09 09:41 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 09:41 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-06-10 00:50 UTC, takattty commented
# 修正内容確認

- [ ] 1-3と同様にresultにエラーメッセージを埋め込む

## 検証結果

![コメント 2022-06-10 094937](https://user-images.githubusercontent.com/43886741/172968576-cdf81a8b-126c-4cf1-a564-cb293a6cd66c.png)

2022-06-10 03:20 UTC, igamasayuki approved these changes
承認します。

気になる点をコメントしました。
承認しますが、次回の入力値チェックと統合する際、意識していただきますようお願い致します。

2022-06-10 03:20 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
単体の改修については問題ありません、
以後の改修にて、入力値チェックの改修と統合した際、全て(未入力値チェックのエラーとEメール重複エラー、パスワード不一致エラー)のエラーメッセージが同時に出るように意識をお願いします。

意味がわからない場合はご相談ください。

2022-06-10 03:21 UTC, merged