1-2 入力値エラー処理の作成
takattty/ex-emp-management-bugfix pull request #2
Opened 2022-06-09 05:22 UTC by takattty

# やった事

- htmlファイルにエラーメッセージや前に入力したデータを表示する属性を追加
- コントローラーのメソッド引数に、 `@Validated` を追加
- formクラスにバリデーションのアノテーションを追加

ご確認よろしくお願いいたします。

2022-06-09 09:14 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 09:14 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/form/LoginForm.java
> +	@Size(min=1, max=127, message="パスワードは1文字以上127文字以内で記載してください")
今回のお客さまからの要望は【管理者を登録する】ユースケースのみのため
【ログインをする】のユースケースの対応は不要です。

【ログインをする】は入力値チェックをせずに、DBに存在するかしないかのみを見て認証するため不要という仕様になります。

2022-06-09 09:14 UTC, igamasayuki commented on src/main/resources/templates/administrator/login.html
> +					<form method="post" action="../employee/list.html" th:action="@{/login}" th:object="${loginForm}">
今回のお客さまからの要望は【管理者を登録する】ユースケースのみのため
【ログインをする】のユースケースの対応は不要です。

【ログインをする】は入力値チェックをせずに、DBに存在するかしないかのみを見て認証するため不要という仕様になります。

2022-06-10 00:01 UTC, takattty commented
# 修正箇所の確認

- [ ] ログインの画面のフィールドや属性を削除
- [ ] ログインフォームのバリデーションを削除
- [ ] 管理者を登録する画面の確認

2022-06-10 03:07 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-06-10 03:08 UTC, merged