1-3 メール重複の際の500エラー画面の表示修正
takattty/ex-emp-management-bugfix pull request #9
Opened 2022-06-09 06:39 UTC by takattty

# やった事

- サービスクラスで先にメールアドレスが登録されているか確認し、無かったらtrueあったらfalseを返す
- コントローラーで、その真偽値を判断しどちらかのページを表示

# 確認した事

- 既に登録されているメアドだと、同じ画面にリダイレクト
- 登録されていないメアドだと、正常に登録

を確認しました。

## 改善が必要だと思う部分

- [ ] エラーメッセージの表示
- [ ] 真偽値の変数名のリファクタリング

表示の修正は終えましたが、まだ上記の点は改善すべきだと思いますので、TODOとして残しておきます。

ご確認よろしくお願いいたします。

2022-06-09 09:39 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 09:39 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +		return false;
行なっていることは問題ありませんが、以下の方針に修正をお願い致します。
入力値チェックと同じようなタイミング(コントローラの最初の方)でチェックを終わらせるようなイメージです。

○今回の方針
　・AdministratorServiceにseachByMailAddress()を作る
　・AdministratorControllerで上記のメソッドを呼ぶ
　・もしnullなら入力画面に戻りエラーメッセージを出す
　・もしnullじゃなければ(Administratorオブジェクトが返ってきたら)登録処理を行う

2022-06-09 09:39 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
今後の改善点として挙げていただいていましたが、やはりエラーメッセージを出していただきたいです。

　また、今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-06-10 00:11 UTC, takattty commented
# 修正内容の確認

2点
- [ ] メールアドレスが既に登録されていて、その結果次第で処理を分岐するのはコントローラーの仕事にする
- [ ] エラーメッセージの出力方法


## メールアドレスが既に登録されていて、その結果次第で処理を分岐するのはコントローラーの仕事にする

○今回の方針
　・AdministratorServiceにseachByMailAddress()を作る
　・AdministratorControllerで上記のメソッドを呼ぶ
　・もしnullなら入力画面に戻りエラーメッセージを出す
　・もしnullじゃなければ(Administratorオブジェクトが返ってきたら)登録処理を行う

これはそのまま実装してみる。
ただもしserviceで調べてユーザーが既に登録されているなら、返り値はAdministratorでエラーメッセージを表示じゃないのかな？？
登録がされていなければ、nullが返ってくるはずなので（リポジトリでそうしてる）その時に登録処理ではないのかな？


##  エラーメッセージの出力方法

> resultにエラーメッセージを追加することができます。

こちらですね。
`result.hasError()` で呼び出しての処理をさしているのかな。
これも動かしながら確認する。

2022-06-10 03:15 UTC, igamasayuki commented
> これはそのまま実装してみる。 ただもしserviceで調べてユーザーが既に登録されているなら、返り値はAdministratorでエラーメッセージを表示じゃないのかな？？ 登録がされていなければ、nullが返ってくるはずなので（リポジトリでそうしてる）その時に登録処理ではないのかな？

ServiceでチェックしていたものをControllerに移していただくことを行いました。
「登録処理」には「重複しているかをチェックする処理」も含むということでServiceでチェックするという意図も理解できますが、重複チェックは入力値チェックやパスワード一致チェックと同様、Controllerの上の方で行い、一括でメッセージを出したいという意図でした。
質問の意図と回答が違っていたり、不明点あればお伝えください。
 
> ## エラーメッセージの出力方法
> > resultにエラーメッセージを追加することができます。
> 
> こちらですね。 `result.hasError()` で呼び出しての処理をさしているのかな。 これも動かしながら確認する。

こちら曖昧でしたねresult変数が参照している「エラーメッセージが入るオブジェクト」に後からエラーメッセージを追加することができるという意味でした。

2022-06-10 03:18 UTC, igamasayuki approved these changes
承認します。

気になる点をコメントしました。
コメントの内容について、入力値チェックと統合する際、意識していただきますようお願い致します。

2022-06-10 03:18 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		}
単体の改修については問題ありません、
以後の改修にて、入力値チェックの改修と統合した際、全て(未入力値チェックのエラーとEメール重複エラー、パスワード不一致エラー)のエラーメッセージが同時に出るように意識をお願いします。

意味がわからない場合はご相談ください。

2022-06-10 03:18 UTC, merged